import Head from "next/head";
import Link from "next/link";
import DewButton from "@/components/DewButton";
import { useEffect, useState } from "react";

interface Space {
  id: string;
  name: string;
}

export default function Home() {
  const [spaces, setSpaces] = useState<Space[]>([]);

  const testSpaceId = "clkn7tzs00008umocjphxpm67";

  useEffect(() => {
    const data = window.localStorage.getItem("my-spaces");
    let mySpaces = [] as Space[];
    if (data) {
      const parsedData = JSON.parse(data) as { spaces: Space[] | undefined };
      if (parsedData.spaces) {
        mySpaces = parsedData.spaces;
      }
    }
    setSpaces(mySpaces);
  }, []);

  const spacesList = spaces.map((space) => {
    return (
      <li key={space.id} className="text-brand-purple">
        <Link href={`/space/${space.id}`}>{space.name}</Link>
      </li>
    );
  });

  return (
    <>
      <Head>
        <title>dewdayte</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]"></div> */}
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col justify-center gap-12 px-4 py-16 ">
          <div className="flex w-full justify-center">
            <h1 className="text-5xl font-extrabold text-brand-purple">
              dewdayte
            </h1>
          </div>
          {Boolean(spaces.length) && (
            <div className="w-full bg-grey-lightest">
              <p>your spaces</p>
              <ul>{spacesList}</ul>
            </div>
          )}
          <h2 className="font-spline text-3xl font-bold">
            get sh*t done
            <br />
            (on time)
          </h2>
          <div className="flex w-full flex-col gap-8">
            <Link href="/space/create">
              <DewButton type="primary">create a new space</DewButton>
            </Link>
          </div>
          <div className="w-full rounded-xl bg-midnight-purple p-6">
            <p className="text-white">just want to test it out?</p>
            <Link href={`/space/${testSpaceId}`}>
              <DewButton type="primary">join the demo space</DewButton>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
